AllCops:
  RunRailsCops: true

  Exclude:
    - bin/**/*
    - config/**/*
    - lib/templates/**/*
    - vendor/**/*

Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

SymbolArray:
  Description: 'Use %i or %I for arrays of symbols.'
  Enabled: true

AlignParameters:
  Enabled: false

LineLength:
  Description: 'Limit lines to 120 characters.'
  Max: 120

Style/AsciiComments:
  Enabled: false
