development:
  secret_key_base: f85f58f0f1c69be461c58b37305d23bbbfcdaa38a735c588cca2b9d8460ff3572ac0a1e50ebf16694a282f94407058d34016a1137741a55c40aba6b3fa8ecc19

test:
  secret_key_base: b7a73ba591259cf1a5d561e2917ee49d23d7ef5d7aaea564d842dbca269e6c93e4c59041531f40a70f02f721b844f0a5a4ce91294d5dae49037a3b06dd8ddb02

staging:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  s3_bucket: <%= ENV['S3_BUCKET'] %>

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  s3_bucket: <%= ENV['S3_BUCKET'] %>